FROM tiangolo/uwsgi-nginx-flask:python3.8

# install ca certificates
RUN apt-get update
RUN apt-get install -y ca-certificates
RUN update-ca-certificates

# install dependencies
COPY requirements.txt requirements.txt
COPY ./app /app
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
RUN apt-get install -y ffmpeg

ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/

VOLUME ["/music"]